# Site settings
title: "Rosemont Ridge Middle School Newspaper"
description: "slogan here"
baseurl: ""
url: "rrmsnewspaper.github.com"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "abt"
    url: /about
  - title: "rrms"
    url: "http://www.rrms.wlwv.k12.or.us/site/default.aspx?PageID=23"
